/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SalonesRouteImport } from './routes/salones'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SalonesIndexRouteImport } from './routes/salones/index'
import { Route as SalonesIdRouteImport } from './routes/salones/$id'
import { Route as SalonesIdReservarRouteImport } from './routes/salones/$id.reservar'

const SalonesRoute = SalonesRouteImport.update({
  id: '/salones',
  path: '/salones',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SalonesIndexRoute = SalonesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SalonesRoute,
} as any)
const SalonesIdRoute = SalonesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SalonesRoute,
} as any)
const SalonesIdReservarRoute = SalonesIdReservarRouteImport.update({
  id: '/reservar',
  path: '/reservar',
  getParentRoute: () => SalonesIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/salones': typeof SalonesRouteWithChildren
  '/salones/$id': typeof SalonesIdRouteWithChildren
  '/salones/': typeof SalonesIndexRoute
  '/salones/$id/reservar': typeof SalonesIdReservarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/salones/$id': typeof SalonesIdRouteWithChildren
  '/salones': typeof SalonesIndexRoute
  '/salones/$id/reservar': typeof SalonesIdReservarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/salones': typeof SalonesRouteWithChildren
  '/salones/$id': typeof SalonesIdRouteWithChildren
  '/salones/': typeof SalonesIndexRoute
  '/salones/$id/reservar': typeof SalonesIdReservarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/salones'
    | '/salones/$id'
    | '/salones/'
    | '/salones/$id/reservar'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/salones/$id' | '/salones' | '/salones/$id/reservar'
  id:
    | '__root__'
    | '/'
    | '/salones'
    | '/salones/$id'
    | '/salones/'
    | '/salones/$id/reservar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SalonesRoute: typeof SalonesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/salones': {
      id: '/salones'
      path: '/salones'
      fullPath: '/salones'
      preLoaderRoute: typeof SalonesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salones/': {
      id: '/salones/'
      path: '/'
      fullPath: '/salones/'
      preLoaderRoute: typeof SalonesIndexRouteImport
      parentRoute: typeof SalonesRoute
    }
    '/salones/$id': {
      id: '/salones/$id'
      path: '/$id'
      fullPath: '/salones/$id'
      preLoaderRoute: typeof SalonesIdRouteImport
      parentRoute: typeof SalonesRoute
    }
    '/salones/$id/reservar': {
      id: '/salones/$id/reservar'
      path: '/reservar'
      fullPath: '/salones/$id/reservar'
      preLoaderRoute: typeof SalonesIdReservarRouteImport
      parentRoute: typeof SalonesIdRoute
    }
  }
}

interface SalonesIdRouteChildren {
  SalonesIdReservarRoute: typeof SalonesIdReservarRoute
}

const SalonesIdRouteChildren: SalonesIdRouteChildren = {
  SalonesIdReservarRoute: SalonesIdReservarRoute,
}

const SalonesIdRouteWithChildren = SalonesIdRoute._addFileChildren(
  SalonesIdRouteChildren,
)

interface SalonesRouteChildren {
  SalonesIdRoute: typeof SalonesIdRouteWithChildren
  SalonesIndexRoute: typeof SalonesIndexRoute
}

const SalonesRouteChildren: SalonesRouteChildren = {
  SalonesIdRoute: SalonesIdRouteWithChildren,
  SalonesIndexRoute: SalonesIndexRoute,
}

const SalonesRouteWithChildren =
  SalonesRoute._addFileChildren(SalonesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SalonesRoute: SalonesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
