/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SalonesRouteImport } from './routes/salones'
import { Route as IndexRouteImport } from './routes/index'

const SalonesRoute = SalonesRouteImport.update({
  id: '/salones',
  path: '/salones',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/salones': typeof SalonesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/salones': typeof SalonesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/salones': typeof SalonesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/salones'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/salones'
  id: '__root__' | '/' | '/salones'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SalonesRoute: typeof SalonesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/salones': {
      id: '/salones'
      path: '/salones'
      fullPath: '/salones'
      preLoaderRoute: typeof SalonesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SalonesRoute: SalonesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
